apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: alerts-dev-enablement
    options:
      disableNameSuffixHash: true
    files:
      - keda-scaler-errors.yaml=scale-errors.yaml
