apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-metrics-apiserver
    app.kubernetes.io/part-of: keda-operator
  name: keda-metrics-apiserver
rules:
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
      - scaledobjects/finalizers
      - scaledobjects/status
    verbs:
      - '*'
  - apiGroups:
      - keda.sh
    resources:
      - triggerauthentications
      - triggerauthentications/status
    verbs:
      - '*'
  - apiGroups:
      - keda.sh
    resources:
      - scaledjobs
      - scaledjobs/finalizers
      - scaledjobs/status
    verbs:
      - '*'
