apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
rules:
  - apiGroups:
      - keda.sh
    resources:
      - clustertriggerauthentications
      - clustertriggerauthentications/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventing.keda.sh
    resources:
      - clustercloudeventsources
      - clustercloudeventsources/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
# TODO [SB] do we actually need these? They appeared in newer version.
#  At least validatingwebhookconfigurations is for validating the resources
#  - apiGroups:
#      - apiregistration.k8s.io
#    resources:
#      - apiservices
#    verbs:
#      - get
#      - list
#      - patch
#      - update
#      - watch
#  - apiGroups:
#      - admissionregistration.k8s.io
#    resources:
#      - validatingwebhookconfigurations
#    verbs:
#      - get
#      - list
#      - patch
#      - update
#      - watch
