apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
rules:
  - apiGroups:
      - keda.sh
    resources:
      - clustertriggerauthentications
      - clustertriggerauthentications/status
    verbs:
      - '*'
