apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.16.0
  name: keda-operator
spec:
  ports:
    - name: metricsservice
      port: 9666
      targetPort: 9666
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: keda-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.16.0
  name: keda-operator
  annotations:
    "app.uw.systems/description": "Kubernetes event-driven autoscaler API operator."
    "app.uw.systems/tier": "tier_2"
    "app.uw.systems/repos.keda-manifests": "https://github.com/utilitywarehouse/keda-manifests/namespaced/operator"
    "app.uw.systems/tags.oss": "true"
    "app.uw.systems/tags.skip-repo": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-operator
  template:
    metadata:
      labels:
        app: keda-operator
        name: keda-operator
      name: keda-operator
    spec:
      containers:
        - args:
            - --leader-elect
            - --zap-log-level=info
            - --zap-encoder=console
            - --zap-time-encoding=rfc3339
            - --enable-cert-rotation=true
          command:
            - /keda
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              value: "TBD"
            - name: KEDA_HTTP_DEFAULT_TIMEOUT
              value: ""
            - name: KEDA_RESTRICT_SECRET_ACCESS
              value: "true"
          image: ghcr.io/kedacore/keda:2.16.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 25
          name: keda-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: ops
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /certs
              name: certificates
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: keda-operator
      terminationGracePeriodSeconds: 10
      volumes:
        - name: certificates
          secret:
            defaultMode: 420
            optional: true
            secretName: kedaorg-certs

