apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
      - external
      - pods
      - secrets
      - services
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - limitranges
      - serviceaccounts
    verbs:
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - '*/scale'
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - eventing.keda.sh
    resources:
      - cloudeventsources
      - cloudeventsources/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keda.sh
    resources:
      - scaledjobs
      - scaledjobs/finalizers
      - scaledjobs/status
      - scaledobjects
      - scaledobjects/finalizers
      - scaledobjects/status
      - triggerauthentications
      - triggerauthentications/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-operator
subjects:
  - kind: ServiceAccount
    name: keda-operator
