apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups:
      - ""
    resources:
      - external
      - pods
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - 'apps'
    resources:
      - 'deployments/scale'
      - 'statefulsets/scale'
      - 'replicasets/scale'
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - keda.sh
    resources:
      - scaledjobs
      - scaledjobs/finalizers
      - scaledjobs/status
    verbs:
      - '*'
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
      - scaledobjects/finalizers
      - scaledobjects/status
    verbs:
      - '*'
  - apiGroups:
      - keda.sh
    resources:
      - triggerauthentications
      - triggerauthentications/status
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-operator
subjects:
  - kind: ServiceAccount
    name: keda-operator
