# We did the following changes to the default cluster role:
#  - removed the access to apiregistration.k8s.io/apiservices and admissionregistration.k8s.io/validatingwebhookconfigurations as those are needed for updating the cabundle when keda is responsible for managing the TLS assets. In our case we're using our own cert manager to do this.
#  - removed the global access to secrets
#  - removed the generic get from all resources
#  - added access to subjectaccessreviews as seems the metrics API server needs it.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
      - external
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - limitranges
      - serviceaccounts
    verbs:
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - '*/scale'
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - watch

  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventing.keda.sh
    resources:
      - cloudeventsources
      - cloudeventsources/status
      - clustercloudeventsources
      - clustercloudeventsources/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keda.sh
    resources:
      - clustertriggerauthentications
      - clustertriggerauthentications/status
      - scaledjobs
      - scaledjobs/finalizers
      - scaledjobs/status
      - scaledobjects
      - scaledobjects/finalizers
      - scaledobjects/status
      - triggerauthentications
      - triggerauthentications/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-operator
subjects:
  - kind: ServiceAccount
    name: keda-operator
    # Running the operator from the dev-enablement namespace
    namespace: dev-enablement
