apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keda-selfsigned-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keda-selfsigned-ca
spec:
  issuerRef:
    kind: Issuer
    name: keda-selfsigned-ca-issuer
  secretName: keda-selfsigned-ca
  commonName: keda
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: keda-selfsigned-issuer
spec:
  ca:
    secretName: keda-selfsigned-ca
