apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    # API service cert is installed in kube-system
    cert-manager.io/inject-ca-from: kube-system/keda-apiservice-cert
  labels:
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.16.1
  name: v1beta1.external.metrics.k8s.io
spec:
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  service:
    name: keda-metrics-apiserver
    # Running the operator from the dev-enablement namespace
    namespace: dev-enablement
  version: v1beta1
  versionPriority: 100
