apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keda-apiservice-cert
spec:
  commonName: keda-apiservice-cert
  duration: 2160h0m0s # 90 days, renews 2/3 of the way through
  issuerRef:
    kind: ClusterIssuer
    name: keda-selfsigned-issuer
  secretName: keda-apiservice-cert
