apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-metrics-apiserver
    app.kubernetes.io/part-of: keda-operator
  name: keda-metrics-apiserver
rules:
  - apiGroups:
      - keda.sh
    resources:
      - scaledjobs
      - scaledjobs/finalizers
      - scaledjobs/status
      - scaledobjects
      - scaledobjects/finalizers
      - scaledobjects/status
      - triggerauthentications
      - triggerauthentications/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
# todo [sb]: needed when operator generates its own certificate
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
