apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
      - external
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - limitranges
      - serviceaccounts
    verbs:
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - '*/scale'
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - watch

  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventing.keda.sh
    resources:
      - cloudeventsources
      - cloudeventsources/status
      - clustercloudeventsources
      - clustercloudeventsources/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keda.sh
    resources:
      - clustertriggerauthentications
      - clustertriggerauthentications/status
      - scaledjobs
      - scaledjobs/finalizers
      - scaledjobs/status
      - scaledobjects
      - scaledobjects/finalizers
      - scaledobjects/status
      - triggerauthentications
      - triggerauthentications/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch

# We don't need this when running with our own certs, otherwise it needs access to be able to update the ca bundle on the APIservice & Validating Webhook.
#  - apiGroups:
#      - apiregistration.k8s.io
#    resources:
#      - apiservices
#    verbs:
#      - get
#      - list
#      - patch
#      - update
#      - watch
#  - apiGroups:
#      - admissionregistration.k8s.io
#    resources:
#      - validatingwebhookconfigurations
#    verbs:
#      - get
#      - list
#      - patch
#      - update
#      - watch
